version: '3'
services:
  wireguard-builder:
    image: wireguard-builder
    container_name: wireguard-builder
    volumes:
      - "/volume1/home/admin/wgmodule:/root/temp" # bind home directory to the container
    restart: no
    command: /bin/cp /root/wireguard.ko /root/temp